global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pg-primary'
    static_configs:
      - targets: ['primary_exporter:9187']

  - job_name: 'pg-replica-01'
    static_configs:
      - targets: ['replica01_exporter:9187']

  - job_name: 'pg-replica-02'
    static_configs:
      - targets: ['replica02_exporter:9187']